site_name: RecVal
repo_url: https://https://github.com/damicoedoardo/recval
site_url: https://damicoedoardo.github.io/recval
site_description: site description.
site_author: Edoardo D'Amico
edit_uri: edit/main/docs/
repo_name: damicoedoardo/recval
# copyright: Maintained by <a href="https://https://github.com/damicoedoardo">Edoardo D'Amico</a>.

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.instant
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  markdown_extensions:
    - toc:
        permalink: True
        toc_depth: 2
    - pymdownx.highlight
    - pymdownx.superfences
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Installation: installation.md
  - Docs: reference/

extra_css:
  - stylesheets/extra.css
