site_name: RecVal
repo_url: https://https://github.com/damicoedoardo/recval
site_url: https://damicoedoardo.github.io/recval
site_description: site description.
site_author: Edoardo D'Amico
edit_uri: edit/main/docs/
repo_name: damicoedoardo/recval
# copyright: Maintained by <a href="https://https://github.com/damicoedoardo">Edoardo D'Amico</a>.

# nav:
#   - Home: index.md
#   - Modules: modules.md
plugins:
  - search
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         setup_commands:
  #           - import sys
  #           - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
# markdown_extensions:
#   - toc:
#       permalink: true
#   - pymdownx.arithmatex:
#       generic: true
