name: Publish to PyPI.org

on:
  release:
    types: [published, edited]

env:
  poetry-version: 1.3.1
  python-version: 3.10.6

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/setup-python@v4
        name: Setup Python
        with:
          python-version: ${{ env.python-version }}

      - uses: abatilo/actions-poetry@v2.1.1
        name: Install Poetry
        with:
          poetry-version: ${{ env.poetry-version }}

      - name: Update Poetry cache location
        run: poetry config virtualenvs.in-project true

      - id: venv_cache
        uses: actions/cache@v3
        name: Cache or Restore venv
        with:
          path: .venv
          key: venv-${{ env.python-version }}-${{ env.poetry-version }}-lock-${{ hashFiles('poetry.lock') }}

      - name: Install Poetry Dependencies
        run: poetry install
        if: steps.venv_cache.outputs.cache-hit != 'true'

      - name: Publish to PyPI
        run: poetry publish --build --username ${{secrets.PYPI_USERNAME}} --password ${{secrets.PYPI_TOKEN}}
